kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    SDK_ACCOUNT:
      from_secret: sdk_account
  commands:
    - echo -E $${SDK_ACCOUNT} > ./credential.json
    - gcloud auth activate-service-account --key-file ./credential.json
    # - rp_reviewdog src/
  when:
    event:
    - pull_request
