ind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python:w
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    CREDENTIAL_KEY:
      from_secret: cred_key
    SA_NAME:
      from_secret: sa_name
    PROJECT_ID:
      from_secret: project_id
    GSQL_REGION: us-central1
    GSQL_INSTANCE_NAME:
      from_secret: db_instance_name
    MYSQL_DATABASE:
      from_secret: db_name
    MYSQL_USER: boat_usr
    MYSQL_HOST: 127.0.0.1
    MYSQL_ENV: TEST
  commands:
    - sleep 30
    - pip install poetry
    - poetry install
    - poetry run rp_pytest src/
    - poetry run rp_reviewdog src/
    - mysql -u test_boat_user -h testmysql --password=test_pw -D test_boat_db -e "show tables;"
  when:
    event:
    - pull_request

services:
- name: testmysql
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test_boat_db
    MYSQL_USER: 'test_boat_user'
    MYSQL_PASSWORD: 'test_pw'

image_pull_secrets:
  - dockerconfig
