kind: pipeline
type: docker
name: default

steps:
- name: cloud-sdk
  pull: always
  image: google/cloud-sdk
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - which gcloud

- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - gcloud init
    - gcloud auth list
    - rp_reviewdog src/
  when:
    event:
    - pull_request
volumes:
  - name: dockersock
    temp: {}
