kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    CREDENTIAL_KEY:
      from_secret: cred_key
  commands:
    - bash -c 'echo -E $${CREDENTIAL_KEY} > /tmp/credential.json'
    - gcloud auth activate-service-account --key-file /tmp/credential.json
    # - rp_reviewdog src/
  when:
    event:
    - pull_request
