kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    # PRIVATE_KEY:
    #   from_secret: github_pri_key
    # APP_ID:
    #   from_secret: app_id
    # INSTALLATION_ID:
    #   from_secret: installation_id
    CREDENTIAL_KEY:
      from_secret: cred_key
    SA_NAME:
      from_secret: sa_name
    PROJECT_ID:
      from_secret: project_id
    GSQL_REGION: us-central1
    GSQL_INSTANCE_NAME:
      from_secret: db_instance_name
    MYSQL_DATABASE:
      from_secret: db_name
    MYSQL_USER: boat_usr
    MYSQL_HOST: 127.0.0.1
  commands:
    - bash -c 'echo -E $${CREDENTIAL_KEY} > /tmp/credential.json'
    - gcloud auth activate-service-account --key-file /tmp/credential.json
    - gcloud config set project $PROJECT_ID
    - source vars_from_secret
    - echo $APP_ID
    - echo $INSTALLATION_ID
    # - export MYSQL_PASSWORD=$(gcloud secrets versions access latest --secret="mysql-usr-pw")
    # - make start_gdb
    # - pipenv install --system
    # - rp_pytest src/module/
    # - rp_reviewdog src/
    # - make down_gdb

  when:
    event:
    - pull_request
